### ISSUE TITLE
doris5.0.3beta prepare_datastack.py dosen't work

### ISSUE THREAD

**Issue by suiuy** [suiuy/studyinsar#1]
when i work python prepare_datastack.py,it dosen't work and feedback an error  File "/home/l/StaMPS/Doris-5.0.3Beta/prepare_stack/create_dem.py", line 16, in <module>
    import gdal
ImportError: No module named gdal.
but i have installed the gdal
i didn't kown where was wrong.need help!

**Comment by suiuy** [comment]
Traceback (most recent call last):
  File "prepare_datastack.py", line 14, in <module>
    from create_dem import CreateDem
  File "/home/l/StaMPS/Doris-5.0.3Beta/prepare_stack/create_dem.py", line 16, in <module>
    import gdal
ImportError: No module named gdal
